default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host:     <%= ENV.fetch('POSTGRESS_HOST', 'localhost') %>
  database: inventory_db2
  username: postgres
  password: 123456

test:
  <<: *default

development:
  <<: *default

deploy_dev:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
